export const cities = {
  ua: [
    "kyiv",
    "kharkiv",
    "odesa",
    "dnipro",
    "donetsk",
    "zaporizhzhia",
    "lviv",
    "kryvyi-rih",
    "mykolaiv",
    "vinnytsia",
    "kherson",
    "poltava",
    "chernihiv",
    "cherkasy",
    "zhytomyr",
    "sumy",
    "rivne",
    "ternopil",
    "lutsk",
    "ivano-frankivsk",
    "kamianske",
    "kropyvnytskyi",
    "khmelnytskyi",
    "chernivtsi",
    "bila-tserkva",
    "kremenchuk",
    "kramatorsk",
    "melitopol",
    "nikopol",
    "uzhhorod",
    "berdiansk",
    "brovary",
    "slavutych",
  ],
} as const;
