export const cities = {
  ua: [
    "Kyiv",
    "Kharkiv",
    "Odesa",
    "Dnipro",
    "Donetsk",
    "Zaporizhzhia",
    "Lviv",
    "Kryvyi Rih",
    "Mykolaiv",
    "Vinnytsia",
    "Kherson",
    "Poltava",
    "Chernihiv",
    "Cherkasy",
    "Zhytomyr",
    "Sumy",
    "Rivne",
    "Ternopil",
    "Lutsk",
    "Ivano Frankivsk",
    "Kamianske",
    "Kropyvnytskyi",
    "Khmelnytskyi",
    "Chernivtsi",
    "Bila Tserkva",
    "Kremenchuk",
    "Kramatorsk",
    "Melitopol",
    "Nikopol",
    "Uzhhorod",
    "Berdiansk",
    "Brovary",
    "Slavutych",
  ],
} as const;

export const citiesUrls = Object.fromEntries(
  Object.entries(cities).map(([key, value]) => [
    key,
    value.map((city) => city.replace(/\s+/g, "-").toLowerCase()),
  ]),
);
